# Generated by Django 4.2.2 on 2023-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='notes',
        ),
        migrations.AddField(
            model_name='password',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
